spring.application.name: ghuserdata

logging.level.org.zalando.logbook: TRACE

logbook:
  format: http
  filter:
    enabled: true
    exclude:
      - /health

clients:
  github:
    baseUrl: "https://api.github.com"
